apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeName: kind-for-assigment-control-plane
      containers:
      - name: frontend
        # image: trideepnandi/nodejs-application:latest
        image: itsmrhashtag/frontend:latest
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: host
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: database_name
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: database_user
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # type: LoadBalancer # in case of ingress
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002